# Generated by Django 2.1.7 on 2019-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('refid', models.CharField(max_length=8)),
                ('good_type', models.CharField(max_length=10)),
                ('packs', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=200)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('usertype', models.CharField(max_length=10)),
            ],
        ),
    ]
