# Generated by Django 2.1.7 on 2019-03-04 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='orderdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
