# Generated by Django 2.1.7 on 2019-03-18 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0003_auto_20190310_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='packs',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='details',
            name='refid',
        ),
        migrations.AlterField(
            model_name='details',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
