# Generated by Django 2.1.7 on 2019-03-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0004_auto_20190319_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='good_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
