# Generated by Django 2.1.7 on 2019-03-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0006_auto_20190331_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='customer_name',
            field=models.CharField(max_length=10),
        ),
    ]
