# Generated by Django 2.1.7 on 2019-03-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0007_auto_20190331_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
