# Generated by Django 2.1.7 on 2019-03-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0009_details_good_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='customer_name',
            new_name='your_name',
        ),
        migrations.AddField(
            model_name='details',
            name='to_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
