# Generated by Django 2.1.7 on 2019-04-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0010_auto_20190331_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
    ]
