# Generated by Django 2.1.7 on 2019-04-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0011_details_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
